
export const item1 = [
    {
        id: 1,
        transactionDepositor: 'xamps',
        transactionReceiver: 'carlosdnba',
        description: 'Corsinha amarelo',
        transactionValue: '20.000,00',
        transactionDate: '6 horas atrás',
        commentsNumber: 12,
        likesNumber: 52,
    },
    {
        id: 2,
        transactionDepositor: 'chefe',
        transactionReceiver: 'carlosdnba',
        description: 'Salário',
        transactionValue: '1.600,00',
        transactionDate: '12 horas atrás',
        commentsNumber: 24,
        likesNumber: 67,
    },
];

export const items2 = [
    {
        id: 1,
        transactionDepositor: 'caraAleatorio',
        transactionReceiver: 'carlosdnba',
        description: 'Freelancer',
        transactionValue: '1000,00',
        transactionDate: '5 dias atrás',
        commentsNumber: 4,
        likesNumber: 29,
    },
    {
        id: 2,
        transactionDepositor: 'chefe',
        transactionReceiver: 'carlosdnba',
        description: 'Salário',
        transactionValue: '1.600,00',
        transactionDate: '12 horas atrás',
        commentsNumber: 24,
        likesNumber: 67,
    },
    {
        id: 3,
        transactionDepositor: 'caraAleatorio',
        transactionReceiver: 'carlosdnba',
        description: 'Freelancer',
        transactionValue: '1000,00',
        transactionDate: '5 dias atrás',
        commentsNumber: 4,
        likesNumber: 29,
    },
    {
        id: 4,
        transactionDepositor: 'chefe',
        transactionReceiver: 'carlosdnba',
        description: 'Salário',
        transactionValue: '1.600,00',
        transactionDate: '12 horas atrás',
        commentsNumber: 24,
        likesNumber: 67,
    },
];

export const items3 = [
    {
        id: 1,
        transactionDepositor: 'caraDaOlx',
        transactionReceiver: 'carlosdnba',
        description: 'Playstation',
        transactionValue: '1200,00',
        transactionDate: '25 dias atrás',
        commentsNumber: 4,
        likesNumber: 29,
    },
    {
        id: 2,
        transactionDepositor: 'chefe',
        transactionReceiver: 'carlosdnba',
        description: 'Salário',
        transactionValue: '1.600,00',
        transactionDate: '30 horas atrás',
        commentsNumber: 24,
        likesNumber: 67,
    },
    {
        id: 3,
        transactionDepositor: 'caraAleatorio',
        transactionReceiver: 'carlosdnba',
        description: 'Freelancer',
        transactionValue: '1000,00',
        transactionDate: '5 dias atrás',
        commentsNumber: 4,
        likesNumber: 29,
    },
    {
        id: 4,
        transactionDepositor: 'chefe',
        transactionReceiver: 'carlosdnba',
        description: 'Salário',
        transactionValue: '1.600,00',
        transactionDate: '12 horas atrás',
        commentsNumber: 24,
        likesNumber: 67,
    },
    {
        id: 5,
        transactionDepositor: 'caraAleatorio',
        transactionReceiver: 'carlosdnba',
        description: 'Freelancer',
        transactionValue: '1000,00',
        transactionDate: '5 dias atrás',
        commentsNumber: 4,
        likesNumber: 29,
    },
    {
        id: 6,
        transactionDepositor: 'chefe',
        transactionReceiver: 'carlosdnba',
        description: 'Salário',
        transactionValue: '1.600,00',
        transactionDate: '12 horas atrás',
        commentsNumber: 24,
        likesNumber: 67,
    },
];